# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  - pwd
  - julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add HTTP#master")'
  - julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add JSON2#master")'
  - julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add URIParser#master")'
  - julia --color=yes -e 'using Pkg; Pkg.REPLMode.pkgstr("add Documenter#master")'
  - julia --color=yes -e 'using Bukdu'
  - cd test
  - julia --color=yes --depwarn=no runtests.jl
  # TODO: coverage

after_success:
  # push coverage results to Codecov
  #- if [[ "$TRAVIS_OS_NAME" == linux ]]; then julia -e 'using Pkg; Pkg.REPLMode.pkgstr("add Coverage#master"); using Coverage; Codecov.submit(Codecov.process_folder())'   ; fi
