# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("Bukdu"); Pkg.test("Bukdu"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  # - julia --color=yes -e 'cd(Pkg.dir("Bukdu")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
